server:
  port: 8081

spring:
  application:
    name: dyshop-api
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.dyshop.common.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-field: deleted   # 全局逻辑删除字段（实体需 @TableLogic）
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.dyshop.api.mapper: debug
